<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add docrequest');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/docrequest.php';
    $dbh_docrequest = new docrequest;

    $object_name = 'dbh_docrequest';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_docrequest.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_docrequest->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_docrequest->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_docrequest->add($arr_form_data);
			$username = "root";
			$pass="projDb_2016";
			$database="sams_db";
			$link = mysqli_connect("localhost", $username, $pass);
		
			@mysqli_connect("localhost", $username, $pass);
			@mysqli_select_db($link, $database);
		
			$current = htmlentities($_SESSION['user']);
		
			$query = mysqli_query($link, "SELECT person_id FROM user WHERE username = '".$_SESSION['user']."'");
			$result = mysqli_fetch_array($query);
			
			mysqli_query($link, "UPDATE `docrequest` SET `user_id` = $result[0]");
			mysqli_close($link);
            

            redirect("listview_docrequest.php?$query_string");
        }
    }
}
require 'subclasses/docrequest_html.php';
$html = new docrequest_html;
$html->draw_header('Add a Document Request', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_controls('add');

$html->draw_footer();