<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('ALLOW_ALL');

$html = new html;
$html->draw_header('About ' . GLOBAL_PROJECT_NAME, $message, $message_type);
$project_name = GLOBAL_PROJECT_NAME;
$msg=<<<EOD
This is a System testing prototype for Debugging purposes of the Student Activities Management System
<br /><br /><b> $project_name is powered by Cobalt</b>
EOD;
$html->display_info($msg);

$html->draw_footer();