<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete student affair head');

if(isset($_GET['SAH_Id']))
{
    $SAH_Id = urldecode($_GET['SAH_Id']);
    require_once 'form_data_student_affair_head.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_student_affair_head.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/student_affair_head.php';
        $dbh_student_affair_head = new student_affair_head;

        $object_name = 'dbh_student_affair_head';
        require 'components/create_form_data.php';

        $dbh_student_affair_head->delete($arr_form_data);


        redirect("listview_student_affair_head.php?$query_string");
    }
}
require 'subclasses/student_affair_head_html.php';
$html = new student_affair_head_html;
$html->draw_header('Delete Student Affair Head', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('SAH_Id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();