<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View document');

if(isset($_GET['Doc_Id']) && isset($_GET['Adviser_Org_SAO_SAO_Id']))
{
    $Doc_Id = urldecode($_GET['Doc_Id']);
    $Adviser_Org_SAO_SAO_Id = urldecode($_GET['Adviser_Org_SAO_SAO_Id']);
    require 'form_data_document.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_back']);

    if($_POST['btn_back'])
    {
        log_action('Pressed cancel button');
        require 'components/query_string_standard.php';
        redirect("listview_document.php?$query_string");
    }
}
require 'subclasses/document_html.php';
$html = new document_html;
$html->draw_header('Detail View: Document', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->detail_view = TRUE;
$html->draw_controls('view');

$html->draw_footer();