<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete org');

if(isset($_GET['Org_Id']))
{
    $Org_Id = urldecode($_GET['Org_Id']);
    require_once 'form_data_org.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_org.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/org.php';
        $dbh_org = new org;

        $object_name = 'dbh_org';
        require 'components/create_form_data.php';

        $dbh_org->delete($arr_form_data);


        redirect("listview_org.php?$query_string");
    }
}
require 'subclasses/org_html.php';
$html = new org_html;
$html->draw_header('Delete Org', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('Org_Id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();