<?php
class document_dd
{
    static $table_name = 'document';
    static $readable_name = 'Document';

    static function load_dictionary()
    {
        $fields = array(
                    'id' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'integer',
                                          'length'=>20,
                                          'required'=>FALSE,
                                          'attribute'=>'primary key',
                                          'control_type'=>'none',
                                          'size'=>'60',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'ID',
                                          'extra'=>'',
                                          'companion'=>'',
                                          'in_listview'=>FALSE,
                                          'char_set_method'=>'generate_num_set',
                                          'char_set_allow_space'=>FALSE,
                                          'extra_chars_allowed'=>'-',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'',
                                          'list_settings'=>array(''),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'normal',
                                          'rpt_column_alignment'=>'center',
                                          'rpt_show_sum'=>TRUE),
                    'name' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'varchar',
                                          'length'=>255,
                                          'required'=>TRUE,
                                          'attribute'=>'',
                                          'control_type'=>'upload',
                                          'size'=>'60',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'Name',
                                          'extra'=>'',
                                          'companion'=>'',
                                          'in_listview'=>TRUE,
                                          'char_set_method'=>'',
                                          'char_set_allow_space'=>TRUE,
                                          'extra_chars_allowed'=>'',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'',
                                          'list_settings'=>array(''),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'normal',
                                          'rpt_column_alignment'=>'left',
                                          'rpt_show_sum'=>FALSE),
                    'description' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'varchar',
                                          'length'=>255,
                                          'required'=>TRUE,
                                          'attribute'=>'',
                                          'control_type'=>'textarea',
                                          'size'=>'58;5',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'Description',
                                          'extra'=>'',
                                          'companion'=>'',
                                          'in_listview'=>TRUE,
                                          'char_set_method'=>'',
                                          'char_set_allow_space'=>TRUE,
                                          'extra_chars_allowed'=>'',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'',
                                          'list_settings'=>array(''),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'normal',
                                          'rpt_column_alignment'=>'left',
                                          'rpt_show_sum'=>FALSE),
                    'file_size' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'integer',
                                          'length'=>20,
                                          'required'=>TRUE,
                                          'attribute'=>'',
                                          'control_type'=>'textbox',
                                          'size'=>'60',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'File Size',
                                          'extra'=>'',
                                          'companion'=>'',
                                          'in_listview'=>TRUE,
                                          'char_set_method'=>'generate_num_set',
                                          'char_set_allow_space'=>FALSE,
                                          'extra_chars_allowed'=>'-',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'',
                                          'list_settings'=>array(''),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'number_format2',
                                          'rpt_column_alignment'=>'right',
                                          'rpt_show_sum'=>TRUE),
                                        'share_option_id' => array('value'=>'',
                                            'nullable'=>FALSE,
                                            'data_type'=>'integer',
                                            'length'=>20,
                                            'required'=>TRUE,
                                            'attribute'=>'foreign key',
                                            'control_type'=>'drop-down list',
                                            'size'=>'60',
                                            'drop_down_has_blank'=>TRUE,
                                            'label'=>'Share Option',
                                            'extra'=>'onchange = "this.form.submit()"',
                                            'companion'=>'',
                                            'in_listview'=>TRUE,
                                            'char_set_method'=>'generate_num_set',
                                            'char_set_allow_space'=>FALSE,
                                            'extra_chars_allowed'=>'-',
                                            'allow_html_tags'=>FALSE,
                                            'trim'=>'trim',
                                            'valid_set'=>array(),
                                            'date_elements'=>array('','',''),
                                            'date_default'=>'',
                                            'list_type'=>'sql generated',
                                            'list_settings'=>array('query' => "SELECT share_option.id AS `Queried_id`, share_option.name FROM share_option ORDER BY `name`",
                                                'list_value' => 'Queried_id',
                                                'list_items' => array('name'),
                                                'list_separators' => array()),
                                            'rpt_in_report'=>TRUE,
                                            'rpt_column_format'=>'normal',
                                            'rpt_column_alignment'=>'center',
                                            'rpt_show_sum'=>TRUE),
                    'organization_id' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'integer',
                                          'length'=>20,
                                          'required'=>FALSE,
                                          'attribute'=>'foreign key',
                                          'control_type'=>'hidden',
                                          'size'=>'60',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'Organization',
                                          'extra'=>'',
                                          'companion'=>'',
                                          'in_listview'=>TRUE,
                                          'char_set_method'=>'generate_num_set',
                                          'char_set_allow_space'=>FALSE,
                                          'extra_chars_allowed'=>'-',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'sql generated',
                                          'list_settings'=>array('query' => "SELECT organization.id AS `Queried_id`, organization.name FROM organization ORDER BY `name`",
                                                                     'list_value' => 'Queried_id',
                                                                     'list_items' => array('name'),
                                                                     'list_separators' => array()),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'normal',
                                          'rpt_column_alignment'=>'center',
                                          'rpt_show_sum'=>TRUE),
                                        'uploader_organization' => array('value'=>'',
                                            'nullable'=>FALSE,
                                            'data_type'=>'integer',
                                            'length'=>20,
                                            'required'=>FALSE,
                                            'attribute'=>'',
                                            'control_type'=>'hidden',
                                            'size'=>'60',
                                            'drop_down_has_blank'=>TRUE,
                                            'label'=>'Uploader Organization',
                                            'extra'=>'',
                                            'companion'=>'',
                                            'in_listview'=>FALSE,
                                            'char_set_method'=>'generate_num_set',
                                            'char_set_allow_space'=>FALSE,
                                            'extra_chars_allowed'=>'-',
                                            'allow_html_tags'=>FALSE,
                                            'trim'=>'trim',
                                            'valid_set'=>array(),
                                            'date_elements'=>array('','',''),
                                            'date_default'=>'',
                                            'list_type'=>'',
                                            'list_settings'=>array(''),
                                            'rpt_in_report'=>TRUE,
                                            'rpt_column_format'=>'normal',
                                            'rpt_column_alignment'=>'center',
                                            'rpt_show_sum'=>TRUE)
                       );
        return $fields;
    }

    static function load_relationships()
    {
        $relations = array(array('type'=>'1-1',
                                 'table'=>'organization',
                                 'alias'=>'organization_id',
                                 'link_parent'=>'id',
                                 'link_child'=>'organization_id',
                                 'link_subtext'=>array('name'),
                                 'where_clause'=>''),
            array('type'=>'1-1',
                'table'=>'share_option',
                'alias'=>'share_option_id',
                'link_parent'=>'id',
                'link_child'=>'share_option_id',
                'link_subtext'=>array('name'),
                'where_clause'=>''));

        return $relations;
    }

    static function load_subclass_info()
    {
        $subclasses = array('html_file'=>'document_html.php',
                            'html_class'=>'document_html',
                            'data_file'=>'document.php',
                            'data_class'=>'document');
        return $subclasses;
    }

}