<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View user has document');

if(isset($_GET['User_User_Id']) && isset($_GET['User_Org_Rep_Org_Rep_Id']) && isset($_GET['User_Org_Rep_Org_Org_Id']) && isset($_GET['User_Org_Rep_Org_SAO_SAO_Id']) && isset($_GET['Document_Doc_Id']) && isset($_GET['Document_docRequest_docRequest_Id']) && isset($_GET['Document_docRequest_SAO_SAO_Id']))
{
    $User_User_Id = urldecode($_GET['User_User_Id']);
    $User_Org_Rep_Org_Rep_Id = urldecode($_GET['User_Org_Rep_Org_Rep_Id']);
    $User_Org_Rep_Org_Org_Id = urldecode($_GET['User_Org_Rep_Org_Org_Id']);
    $User_Org_Rep_Org_SAO_SAO_Id = urldecode($_GET['User_Org_Rep_Org_SAO_SAO_Id']);
    $Document_Doc_Id = urldecode($_GET['Document_Doc_Id']);
    $Document_docRequest_docRequest_Id = urldecode($_GET['Document_docRequest_docRequest_Id']);
    $Document_docRequest_SAO_SAO_Id = urldecode($_GET['Document_docRequest_SAO_SAO_Id']);
    require 'form_data_user_has_document.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_back']);

    if($_POST['btn_back'])
    {
        log_action('Pressed cancel button');
        require 'components/query_string_standard.php';
        redirect("listview_user_has_document.php?$query_string");
    }
}
require 'subclasses/user_has_document_html.php';
$html = new user_has_document_html;
$html->draw_header('Detail View: User Has Document', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->detail_view = TRUE;
$html->draw_controls('view');

$html->draw_footer();