<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete docrequest');

if(isset($_GET['docRequest_Id']) && isset($_GET['SAO_SAO_Id']))
{
    $docRequest_Id = urldecode($_GET['docRequest_Id']);
    $SAO_SAO_Id = urldecode($_GET['SAO_SAO_Id']);
    require_once 'form_data_docrequest.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_docrequest.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/docrequest.php';
        $dbh_docrequest = new docrequest;

        $object_name = 'dbh_docrequest';
        require 'components/create_form_data.php';

        $dbh_docrequest->delete($arr_form_data);


        redirect("listview_docrequest.php?$query_string");
    }
}
require 'subclasses/docrequest_html.php';
$html = new docrequest_html;
$html->draw_header('Delete Docrequest', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('docRequest_Id');
$html->draw_hidden('SAO_SAO_Id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();