<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete calevent has org');

if(isset($_GET['calEvent_calEvent_Id']) && isset($_GET['calEvent_SAO_SAO_Id']) && isset($_GET['Org_Org_Id']) && isset($_GET['Org_SAO_SAO_Id']))
{
    $calEvent_calEvent_Id = urldecode($_GET['calEvent_calEvent_Id']);
    $calEvent_SAO_SAO_Id = urldecode($_GET['calEvent_SAO_SAO_Id']);
    $Org_Org_Id = urldecode($_GET['Org_Org_Id']);
    $Org_SAO_SAO_Id = urldecode($_GET['Org_SAO_SAO_Id']);
    require_once 'form_data_calevent_has_org.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_calevent_has_org.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/calevent_has_org.php';
        $dbh_calevent_has_org = new calevent_has_org;

        $object_name = 'dbh_calevent_has_org';
        require 'components/create_form_data.php';

        $dbh_calevent_has_org->delete($arr_form_data);


        redirect("listview_calevent_has_org.php?$query_string");
    }
}
require 'subclasses/calevent_has_org_html.php';
$html = new calevent_has_org_html;
$html->draw_header('Delete Calevent Has Org', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('calEvent_calEvent_Id');
$html->draw_hidden('calEvent_SAO_SAO_Id');
$html->draw_hidden('Org_Org_Id');
$html->draw_hidden('Org_SAO_SAO_Id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();