<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete user has document');

if(isset($_GET['User_User_Id']) && isset($_GET['User_Org_Rep_Org_Rep_Id']) && isset($_GET['User_Org_Rep_Org_Org_Id']) && isset($_GET['User_Org_Rep_Org_SAO_SAO_Id']) && isset($_GET['Document_Doc_Id']) && isset($_GET['Document_docRequest_docRequest_Id']) && isset($_GET['Document_docRequest_SAO_SAO_Id']))
{
    $User_User_Id = urldecode($_GET['User_User_Id']);
    $User_Org_Rep_Org_Rep_Id = urldecode($_GET['User_Org_Rep_Org_Rep_Id']);
    $User_Org_Rep_Org_Org_Id = urldecode($_GET['User_Org_Rep_Org_Org_Id']);
    $User_Org_Rep_Org_SAO_SAO_Id = urldecode($_GET['User_Org_Rep_Org_SAO_SAO_Id']);
    $Document_Doc_Id = urldecode($_GET['Document_Doc_Id']);
    $Document_docRequest_docRequest_Id = urldecode($_GET['Document_docRequest_docRequest_Id']);
    $Document_docRequest_SAO_SAO_Id = urldecode($_GET['Document_docRequest_SAO_SAO_Id']);
    require_once 'form_data_user_has_document.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_user_has_document.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/user_has_document.php';
        $dbh_user_has_document = new user_has_document;

        $object_name = 'dbh_user_has_document';
        require 'components/create_form_data.php';

        $dbh_user_has_document->delete($arr_form_data);


        redirect("listview_user_has_document.php?$query_string");
    }
}
require 'subclasses/user_has_document_html.php';
$html = new user_has_document_html;
$html->draw_header('Delete User Has Document', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('User_User_Id');
$html->draw_hidden('User_Org_Rep_Org_Rep_Id');
$html->draw_hidden('User_Org_Rep_Org_Org_Id');
$html->draw_hidden('User_Org_Rep_Org_SAO_SAO_Id');
$html->draw_hidden('Document_Doc_Id');
$html->draw_hidden('Document_docRequest_docRequest_Id');
$html->draw_hidden('Document_docRequest_SAO_SAO_Id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();