<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete migration');

if(isset($_GET['version']))
{
    $version = urldecode($_GET['version']);
    require_once 'form_data_migration.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_migration.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/migration.php';
        $dbh_migration = new migration;

        $object_name = 'dbh_migration';
        require 'components/create_form_data.php';

        $dbh_migration->delete($arr_form_data);


        redirect("listview_migration.php?$query_string");
    }
}
require 'subclasses/migration_html.php';
$html = new migration_html;
$html->draw_header('Delete Migration', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('version');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();