<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit user has document');

if(isset($_GET['User_User_Id']) && isset($_GET['User_Org_Rep_Org_Rep_Id']) && isset($_GET['User_Org_Rep_Org_Org_Id']) && isset($_GET['User_Org_Rep_Org_SAO_SAO_Id']) && isset($_GET['Document_Doc_Id']) && isset($_GET['Document_docRequest_docRequest_Id']) && isset($_GET['Document_docRequest_SAO_SAO_Id']))
{
    $User_User_Id = urldecode($_GET['User_User_Id']);
    $User_Org_Rep_Org_Rep_Id = urldecode($_GET['User_Org_Rep_Org_Rep_Id']);
    $User_Org_Rep_Org_Org_Id = urldecode($_GET['User_Org_Rep_Org_Org_Id']);
    $User_Org_Rep_Org_SAO_SAO_Id = urldecode($_GET['User_Org_Rep_Org_SAO_SAO_Id']);
    $Document_Doc_Id = urldecode($_GET['Document_Doc_Id']);
    $Document_docRequest_docRequest_Id = urldecode($_GET['Document_docRequest_docRequest_Id']);
    $Document_docRequest_SAO_SAO_Id = urldecode($_GET['Document_docRequest_SAO_SAO_Id']);
    require 'form_data_user_has_document.php';
    $orig_User_User_Id = $User_User_Id;
    $orig_User_Org_Rep_Org_Rep_Id = $User_Org_Rep_Org_Rep_Id;
    $orig_User_Org_Rep_Org_Org_Id = $User_Org_Rep_Org_Org_Id;
    $orig_User_Org_Rep_Org_SAO_SAO_Id = $User_Org_Rep_Org_SAO_SAO_Id;
    $orig_Document_Doc_Id = $Document_Doc_Id;
    $orig_Document_docRequest_docRequest_Id = $Document_docRequest_docRequest_Id;
    $orig_Document_docRequest_SAO_SAO_Id = $Document_docRequest_SAO_SAO_Id;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/user_has_document.php';
    $dbh_user_has_document = new user_has_document;

    $object_name = 'dbh_user_has_document';
    require 'components/create_form_data.php';
    $arr_form_data['orig_User_User_Id'] = $_POST['orig_User_User_Id'];
    $arr_form_data['orig_User_Org_Rep_Org_Rep_Id'] = $_POST['orig_User_Org_Rep_Org_Rep_Id'];
    $arr_form_data['orig_User_Org_Rep_Org_Org_Id'] = $_POST['orig_User_Org_Rep_Org_Org_Id'];
    $arr_form_data['orig_User_Org_Rep_Org_SAO_SAO_Id'] = $_POST['orig_User_Org_Rep_Org_SAO_SAO_Id'];
    $arr_form_data['orig_Document_Doc_Id'] = $_POST['orig_Document_Doc_Id'];
    $arr_form_data['orig_Document_docRequest_docRequest_Id'] = $_POST['orig_Document_docRequest_docRequest_Id'];
    $arr_form_data['orig_Document_docRequest_SAO_SAO_Id'] = $_POST['orig_Document_docRequest_SAO_SAO_Id'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_user_has_document.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_user_has_document->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_user_has_document->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_user_has_document->edit($arr_form_data);


            redirect("listview_user_has_document.php?$query_string");
        }
    }
}
require 'subclasses/user_has_document_html.php';
$html = new user_has_document_html;
$html->draw_header('Edit User Has Document', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_User_User_Id');
$html->draw_hidden('orig_User_Org_Rep_Org_Rep_Id');
$html->draw_hidden('orig_User_Org_Rep_Org_Org_Id');
$html->draw_hidden('orig_User_Org_Rep_Org_SAO_SAO_Id');
$html->draw_hidden('orig_Document_Doc_Id');
$html->draw_hidden('orig_Document_docRequest_docRequest_Id');
$html->draw_hidden('orig_Document_docRequest_SAO_SAO_Id');
$html->draw_controls('edit');

$html->draw_footer();