<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete org rep');

if(isset($_GET['id']) && isset($_GET['Org_Org_Id']) && isset($_GET['Org_SAO_SAO_Id']))
{
    $id = urldecode($_GET['id']);
    $Org_Org_Id = urldecode($_GET['Org_Org_Id']);
    $Org_SAO_SAO_Id = urldecode($_GET['Org_SAO_SAO_Id']);
    require_once 'form_data_org_rep.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_org_rep.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/org_rep.php';
        $dbh_org_rep = new org_rep;

        $object_name = 'dbh_org_rep';
        require 'components/create_form_data.php';

        $dbh_org_rep->delete($arr_form_data);


        redirect("listview_org_rep.php?$query_string");
    }
}
require 'subclasses/org_rep_html.php';
$html = new org_rep_html;
$html->draw_header('Delete Org Rep', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('id');
$html->draw_hidden('Org_Org_Id');
$html->draw_hidden('Org_SAO_SAO_Id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();