<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete document');

if(isset($_GET['id']) && isset($_GET['docRequest_docRequest_Id']) && isset($_GET['docRequest_SAO_SAO_Id']) && isset($_GET['Adviser_Adv_Id']) && isset($_GET['Adviser_Org_Org_Id']) && isset($_GET['Adviser_Org_SAO_SAO_Id']) && isset($_GET['Student Affair Head_SAH_Id']) && isset($_GET['SAO_SAO_Id']))
{
    $id = urldecode($_GET['id']);
    $docRequest_docRequest_Id = urldecode($_GET['docRequest_docRequest_Id']);
    $docRequest_SAO_SAO_Id = urldecode($_GET['docRequest_SAO_SAO_Id']);
    $Adviser_Adv_Id = urldecode($_GET['Adviser_Adv_Id']);
    $Adviser_Org_Org_Id = urldecode($_GET['Adviser_Org_Org_Id']);
    $Adviser_Org_SAO_SAO_Id = urldecode($_GET['Adviser_Org_SAO_SAO_Id']);
    $Student Affair Head_SAH_Id = urldecode($_GET['Student Affair Head_SAH_Id']);
    $SAO_SAO_Id = urldecode($_GET['SAO_SAO_Id']);
    require_once 'form_data_document.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_document.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/document.php';
        $dbh_document = new document;

        $object_name = 'dbh_document';
        require 'components/create_form_data.php';

        $dbh_document->delete($arr_form_data);


        redirect("listview_document.php?$query_string");
    }
}
require 'subclasses/document_html.php';
$html = new document_html;
$html->draw_header('Delete Document', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('id');
$html->draw_hidden('docRequest_docRequest_Id');
$html->draw_hidden('docRequest_SAO_SAO_Id');
$html->draw_hidden('Adviser_Adv_Id');
$html->draw_hidden('Adviser_Org_Org_Id');
$html->draw_hidden('Adviser_Org_SAO_SAO_Id');
$html->draw_hidden('Student Affair Head_SAH_Id');
$html->draw_hidden('SAO_SAO_Id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();