<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit calevent');

if(isset($_GET['id']) && isset($_GET['SAO_SAO_Id']))
{
    $id = urldecode($_GET['id']);
    $SAO_SAO_Id = urldecode($_GET['SAO_SAO_Id']);
    require 'form_data_calevent.php';
    $orig_SAO_SAO_Id = $SAO_SAO_Id;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/calevent.php';
    $dbh_calevent = new calevent;

    $object_name = 'dbh_calevent';
    require 'components/create_form_data.php';
    $arr_form_data['orig_SAO_SAO_Id'] = $_POST['orig_SAO_SAO_Id'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_calevent.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_calevent->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_calevent->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_calevent->edit($arr_form_data);


            redirect("listview_calevent.php?$query_string");
        }
    }
}
require 'subclasses/calevent_html.php';
$html = new calevent_html;
$html->draw_header('Edit Calevent', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('id');
$html->draw_hidden('orig_SAO_SAO_Id');
$html->draw_controls('edit');

$html->draw_footer();